name: osparcli
services:
  postgres:
    command:
      - postgres
      - -c
      - tcp_keepalives_idle=600
      - -c
      - tcp_keepalives_interval=600
      - -c
      - tcp_keepalives_count=5
      - -c
      - max_connections=413
      - -c
      - shared_buffers=256MB
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_USER: scu
    hostname: '{{.Node.Hostname}}-{{.Service.Name}}-{{.Task.Slot}}'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - --username
        - scu
        - --dbname
        - db
      interval: 15s
      retries: 5
    image: postgres:10.11@sha256:2aef165ab4f30fbb109e88959271d8b57489790ea13a77d27c02d8adb8feb20f
    init: true
    networks:
      default: null
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume: {}
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: "16000000000"
  rabbit:
    environment:
      RABBITMQ_DEFAULT_PASS: adminadmin
      RABBITMQ_DEFAULT_USER: admin
    hostname: '{{.Node.Hostname}}-{{.Service.Name}}-{{.Task.Slot}}'
    healthcheck:
      test:
        - CMD-SHELL
        - rabbitmq-diagnostics -q status
      timeout: 30s
      interval: 5s
      retries: 5
      start_period: 5s
    image: itisfoundation/rabbitmq:3.11.2-management
    init: true
    networks:
      default: null
    volumes:
      - type: volume
        source: rabbit_data
        target: /var/lib/rabbitmq
        volume: {}
  web:
    command:
      - python
      - /src/web.py
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://127.0.0.1:8000/health
      timeout: 10s
      interval: 5s
      retries: 3
      start_period: 1s
    image: local/mini-osparc
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    user: 1000:1000
    volumes:
      - type: bind
        source: /home/crespo/repos/osparcli/services
        target: /src
        bind:
          create_host_path: true
networks:
  default:
    name: osparcli_default
volumes:
  postgres_data:
    name: osparcli_postgres_data
  rabbit_data:
    name: osparcli_rabbit_data
